config/routes.rb
Rails.application.routes.draw do

  get 'draft/index'
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'users', to: 'users#index'
    resources :users, only: [:edit, :show, :destroy, :update]
    resources :genres, only: [:edit, :new, :index, :update, :create, :destroy]
  end

  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
    end
    resources :follows, only:[:index]
    resources :posts, only: [:index, :show, :edit, :new, :create, :destroy, :update]
    resources :draft, only: [:index]
    get '/draft', to: 'public/draft#index', as: 'draft'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @genre = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :new
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    if genre.destroy
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_enable)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集フォーム</h1>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件エラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre, url: admin_genre_path, method: :put do |f| %>
  <h4>ツール名</h4>
  <%= f.text_field :name %>

  <div class="field">
  <%= f.check_box :is_enable, {}, "true", "false" %>
  <%= label_tag :is_enable, "有効" %>
  </div>

  <%= f.submit '編集' %>
<% end %>

app/views/admin/genres/index.html.erb
<h1>全ジャンル一覧</h1>
<%= link_to "新規登録" , new_admin_genre_path, method: :get %>
<ul>
  <% @genre.each do |genre| %>
      <li>
        <%= genre.name %>
        <%= link_to "編集" , edit_admin_genre_path(genre.id), method: :get %>
        <%= link_to "削除" , admin_genre_path(genre.id), method: :delete, data: {confirm: "削除しますか？"}  %>
      </li>
  <% end %>
</ul>

app/views/admin/genres/new.html.erb
<h1>ジャンル新規登録フォーム</h1>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件エラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
  <h4>ツール名</h4>
  <%= f.text_field :name %>

  <div class="field">
  <%= f.check_box :is_enable, {}, "true", "false" %>
  <%= label_tag :is_enable, "有効" %>
  </div>

  <%= f.submit '登録' %>
<% end %>