config/routes.rb
Rails.application.routes.draw do

  get 'draft/index'
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'users', to: 'users#index'
    resources :users, only: [:edit, :show, :destroy, :update]
    resources :genres, only: [:edit, :new, :index, :update, :create, :destroy]
  end

  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
    end
    resources :follows, only:[:index]
    resources :posts, only: [:index, :show, :edit, :new, :create, :destroy, :update]
    resources :draft, only: [:index]
    get '/draft', to: 'public/draft#index', as: 'draft'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :follows, dependent: :destroy

  has_one_attached :profile_image

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/, message: "is invalid. Input full-width katakana characters."}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/, message: "is invalid. Input full-width katakana characters."}
  validates :user_name, presence: true
  validates :email, presence: true

 def get_profile_image
  if profile_image.attached?
    profile_image
  else
    'no_image.jpg'
  end
 end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @user = User.where(is_delete: false)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :profile_imag, :is_admin)
  end

  def is_delete_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :profile_imag, :is_delete)
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>ユーザー編集</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>件エラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, url: admin_user_path(@user.id) ,method: :put do |f| %>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name_kana %><br />
    <%= f.text_field :last_name_kana %>
  </div>

  <div class="field">
    <%= f.label :first_name_kana %><br />
    <%= f.text_field :first_name_kana %>
  </div>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </div>

  <div class="field">
  <%= f.check_box :is_admin, {}, "true", "false" %>
  <%= label_tag :is_admin, "管理者権限を付与する" %>
  </div>
  <%= f.submit "更新" %>

<% end %>

<%= link_to "退会", admin_user_path(@user.id), method: :delete %>

<%= link_to "戻る", admin_user_path(@user.id), method: :get %>

app/views/admin/users/index.html.erb
<h1>全ユーザ一覧</h1>
<ul>
  <% @user.each do |user| %>
      <li>
        <%= link_to user.last_name+user.first_name , admin_user_path(user.id), method: :get %> : <%= user.email %>
      </li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h1>ツール投稿フォーム</h1>

<% if @post.errors.any? %>
  <%= @post.errors.count %>件エラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post, method: :post do |f| %>
  <h4>ツール名</h4>
  <%= f.text_field :tool_name %>
  <h4>説明</h4>
  <%= f.text_area :tool_description %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>ジャンル</h4>
  <%= f.text_field :genre_id %>
  <h4>資格名</h4>
  <%= f.text_field :qualification_name %>
  <h4>URL</h4>
  <%= f.text_field :url %>

  <%= f.submit '投稿' %>
<% end %>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>
<%= form_with model: @user do |f| %>
  <h4>ユーザーネーム</h4>
  <%= @user.user_name %>
  <h4>画像</h4>
  <%= image_tag @user.get_profile_image, size: "100x100"%>
  <%= link_to "編集", edit_admin_user_path, method: :get %>
<% end %>
<% @posts.each do |post| %>
  <div>
    <%= image_tag post.get_image, size: "200x200"%>
    <p>ツール名：<%= post.tool_name %></p>
    <p>説明：<%= post.tool_description %></p>
    <p>資格名：<%= post.qualification_name %></p>
    <p>ユーザー名：<%= link_to post.user.user_name, admin_user_path(post.user.id) %></p>
  </div>
<% end %>
<%= link_to "戻る", admin_users_path, method: :get %>